In [9]:
# LAB 1: Welcome to Machine Learning
# Student name: Shaikh Arefin Zaman
# Student ID: 20245103347
print("Hello, future ML detective!")
print("Rule 1: The computer is literal, not rude.")

Hello, future ML detective!
Rule 1: The computer is literal, not rude.

In [10]:
## NumPy Exercises

import numpy as np
np.random.seed(42)
marks = np.array([55, 72, 48, 90, 66, 81])
print('Marks:', marks)
print('Mean:', marks.mean())
print('Highest:', marks.max())
print('Passed:', marks[marks >= 50])

Marks: [55 72 48 90 66 81]
Mean: 68.66666666666667
Highest: 90
Passed: [55 72 90 66 81]

In [11]:
## NumPy Exercises : Task

import numpy as np
np.random.seed(42)
marks = np.array([55, 72, 48, 90, 66, 81])
print('Min : ',marks.min())
print('Standard Deviation : ', marks.std())
print('Bonus Mark : ',marks+5)
print('Original Mark : ',marks)
print("Number of students passed is : ",len(marks[marks >= 50]))

print("\nStatic version : ")
two_d_marks = np.array([
    [55,72,48],
    [90,66,81]
])
print(two_d_marks)

print("\nDynamic version : ")
matrix = marks.reshape(2, 3)
print(matrix)

Min :  48
Standard Deviation :  14.372040758206733
Bonus Mark :  [60 77 53 95 71 86]
Original Mark :  [55 72 48 90 66 81]
Number of students passed is :  5

Static version :
[[55 72 48]
 [90 66 81]]

Dynamic version :
[[55 72 48]
 [90 66 81]]

In [12]:
## Pandas Exercises

import pandas as pd
data = {
'student': ['Asha', 'Babu', 'Chayan', 'Dipa', 'Emon', 'Farah'],
'study_hours': [2, 5, 1, 7, 3, 6],
'sleep_hours': [8, 6, 9, 5, 7, 6],
'attendance': [70, 88, 55, 95, 75, 91],
'snacks': [3, 2, 5, 1, 4, 2],
'passed': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)
display(df)
print(df.info())
print(df.describe())

  student  study_hours  sleep_hours  attendance  snacks passed
0    Asha            2            8          70       3    Yes
1    Babu            5            6          88       2    Yes
2  Chayan            1            9          55       5     No
3    Dipa            7            5          95       1    Yes
4    Emon            3            7          75       4     No
5   Farah            6            6          91       2    Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student      6 non-null      object
 1   study_hours  6 non-null      int64
 2   sleep_hours  6 non-null      int64
 3   attendance   6 non-null      int64
 4   snacks       6 non-null      int64
 5   passed       6 non-null      object
dtypes: int64(4), object(2)
memory usage: 420.0+ bytes
None
       study_hours  sleep_hours  attendance    snacks
count     6.000000     6.000000    6.000000  6.000000
mean      4.000000     6.833333   79.000000  2.833333
std       2.366432     1.471960   15.192103  1.471960
min       1.000000     5.000000   55.000000  1.000000
25%       2.250000     6.000000   71.250000  2.000000
50%       4.000000     6.500000   81.500000  2.500000
75%       5.750000     7.750000   90.250000  3.750000
max       7.000000     9.000000   95.000000  5.000000

In [13]:
## Pandas Exercises : Task

import pandas as pd
data = {
'student': ['Asha', 'Babu', 'Chayan', 'Dipa', 'Emon', 'Farah'],
'study_hours': [2, 5, 1, 7, 3, 6],
'sleep_hours': [8, 6, 9, 5, 7, 6],
'attendance': [70, 88, 55, 95, 75, 91],
'snacks': [3, 2, 5, 1, 4, 2],
'passed': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)
display(df)
print("Features are : study_hours,sleep_hours,attendance,snacks,passed")
print("Label is : passed")
print('Number of sample presents : ',df.shape)
print("\n\nStudents list whom attendacne percentage is greater than 80 : \n",df[df['attendance'] >= 80])
print("\n\nAverage study hours : ",df[df['passed'] == 'Yes']['study_hours'].mean())
print("\n\nSorting the Dataframe by attendace in descending order : \n",df.sort_values('attendance', ascending=False))

print('''\n\nNo, this tiny dataset does not prove that snack purchases cause failure.
It only shows a pattern or possible correlation between snacks and passing/failing.
Correlation can be a clue, but it does not prove causation because other factors,
 such as study hours, attendance, or sleep, may also affect the result.''')

  student  study_hours  sleep_hours  attendance  snacks passed
0    Asha            2            8          70       3    Yes
1    Babu            5            6          88       2    Yes
2  Chayan            1            9          55       5     No
3    Dipa            7            5          95       1    Yes
4    Emon            3            7          75       4     No
5   Farah            6            6          91       2    Yes

Features are : study_hours,sleep_hours,attendance,snacks,passed
Label is : passed
Number of sample presents :  (6, 6)


Students list whom attendacne percentage is greater than 80 :
   student  study_hours  sleep_hours  attendance  snacks passed
1    Babu            5            6          88       2    Yes
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes


Average study hours :  5.0


Sorting the Dataframe by attendace in descending order :
   student  study_hours  sleep_hours  attendance  snacks passed
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes
1    Babu            5            6          88       2    Yes
4    Emon            3            7          75       4     No
0    Asha            2            8          70       3    Yes
2  Chayan            1            9          55       5     No


No, this tiny dataset does not prove that snack purchases cause failure.
It only shows a pattern or possible correlation between snacks and passing/failing.
Correlation can be a clue, but it does not prove causation because other factors,
 such as study hours, attendance, or sleep, may also affect the result.

In [14]:
import random
import numpy as np

def generate_scores(use_seed):
  if use_seed:
    random.seed(42)
    np.random.seed(42)
  return np.random.randint(40, 101, size=5)

print('Seeded run 1:', generate_scores(True))
print('Seeded run 2:', generate_scores(True))
print('Unseeded run 1:', generate_scores(False))
print('Unseeded run 2:', generate_scores(False))

print(''' No, we cannot fairly compare them because different random
 splits can produce different accuracies; for a fair comparison, both
 models should use the same data split or cross-validation procedure.''')

Seeded run 1: [78 91 68 54 82]
Seeded run 2: [78 91 68 54 82]
Unseeded run 1: [ 47 100  60  78  97]
Unseeded run 2: [58 62 50 50 63]
 No, we cannot fairly compare them because different random
 splits can produce different accuracies; for a fair comparison, both
 models should use the same data split or cross-validation procedure.